
fullnameOverride: "exercises-start-points"

replicaCount: 1

envFromSecret: {}
nodeSelector: {}
affinity: {}
tolerations: []

service:
  annotations:
    prometheus.io/scrape: "true"

volumes:
  - name: exercises-start-points-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "16Mi"
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: File

containers:
  - name: exercises-start-points
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: exercises-start-points-tmp-dir
        mountPath: /tmp
        readOnly: false
      - mountPath: /var/run/docker.sock
        name: docker-socket
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        memory: 64Mi
    livenessProbe:
      path: /alive
    readinessProbe:
      path: /ready
    env:
      CYBER_DOJO_PROMETHEUS: "true"
      CYBER_DOJO_EXERCISES_START_POINTS_PORT: "4525"
      # CYBER_DOJO_K8S_PORT: "19661"
